### ISSUE TITLE
开源协议

### ISSUE THREAD

**Issue by machsix** [syhyz1990/media#8]
你好，请问这个脚本的开源协议是什么？这里有一个脚本https://greasyfork.org/zh-CN/scripts/394288-%E8%A7%A3%E6%9E%90%E5%90%84%E5%A4%A7%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99vip%E8%A7%86%E9%A2%91-%E6%94%AF%E6%8C%81%E4%BC%98%E9%85%B7-%E7%88%B1%E5%A5%87%E8%89%BA-%E4%B9%90%E8%A7%86-%E8%85%BE%E8%AE%AF%E8%A7%86%E9%A2%91-%E5%9C%9F%E8%B1%86-%E8%8A%92%E6%9E%9Ctv-bilibili-pptv-%E6%9A%B4%E9%A3%8E-%E9%9F%B3%E6%82%A6%E5%8F%B0/code

不知是否算违规使用你的代码

**Comment by syhyz1990** [comment]
感谢反馈，mit开源协议



---原始邮件---
发件人: "MachX"<notifications@github.com&gt;
发送时间: 2020年1月14日(周二) 凌晨5:59
收件人: "syhyz1990/media"<media@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/media] 开源协议 (#8)



你好，请问这个脚本的开源协议是什么？这里有一个脚本https://greasyfork.org/zh-CN/scripts/394288-%E8%A7%A3%E6%9E%90%E5%90%84%E5%A4%A7%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99vip%E8%A7%86%E9%A2%91-%E6%94%AF%E6%8C%81%E4%BC%98%E9%85%B7-%E7%88%B1%E5%A5%87%E8%89%BA-%E4%B9%90%E8%A7%86-%E8%85%BE%E8%AE%AF%E8%A7%86%E9%A2%91-%E5%9C%9F%E8%B1%86-%E8%8A%92%E6%9E%9Ctv-bilibili-pptv-%E6%9A%B4%E9%A3%8E-%E9%9F%B3%E6%82%A6%E5%8F%B0/code
 
不知是否算违规使用你的代码
